from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import main, him, er, laboratory, enurse,lab_result

urlpatterns = [
    path('', main.index, name='index'),
    path('opd', main.opd, name='opd'),
    path('retrieval', main.opd_retrieval, name='retrieval'),
    path('printing', main.opd_printing, name='printing'),
    path('<str:page>/lookup', main.patient_search, name='lookup'),
    path('patientsearchopd', main.patient_search_opd, name='patientsearchopd'),
    path('<str:page>/lookuprfid', main.patient_search_rfid, name='lookuprfid'),
    path('enc_lookup', main.enc_patient_search, name='enc_lookup'),
    path('newpatient', main.new_patient, name='newpatient'),
    path('<str:no>/<str:page>/patientdetails', main.patientDetails, name='patientdetails'),
    path('<str:no>/patientdetailsopd', main.patientDetailsOPD, name='patientdetailsopd'),
    path('<str:hpercode>/<str:page>/patient_encounter', main.patient_encounter, name='patient_encounter'),
    path('<str:no>/consultations', main.consultations, name='consultations'),
    path('<str:enctr>/<str:typ>/consultationdetails', main.consultation_details, name='consultationdetails'),
    path('<str:enctr>/opdrecord', main.print_opd_record, name='opdrecord'),
    path('<str:no>/opdlog', main.log_opd, name='opdlog'),
    path('opdtriage', main.opd_triage, name='opdtriage'),
    path('<str:uid>/opdtriagelog', main.opd_patient_triage, name='opdtriagelog'),
    path('<str:enctr>/<str:cert_no>/medcert', main.print_medical_cert, name='medcert'),
    path('getMunicipality', main.getMunicipality, name='getMunicipality'),
    path('getBarangay', main.getBarangay, name='getBarangay'),

    path('laboratory', laboratory.laboratory, name='laboratory'),
    path('laboratoryopd', main.laboratory_opd, name='laboratoryopd'),
    path('laboratoryer', main.laboratory_er, name='laboratoryer'),
    path('search_patient',laboratory.search_patient,name='search_patient'),

    ######################## PRINT C
    path('makepdf',laboratory.makepdf,name='makepdf'),
    path('print_c/<str:encc>/<str:orderid>',laboratory.print_c,name='print_c'),
    #pdf

    path('pdfview',laboratory.pdfview,name='pdfview'),
    # ///////laboratory new
   
    ############################# UPLOAD HEMA RESULT
    path('upload_hema',laboratory.upload_hema,name='upload_hema'),
    path('csv_upload',laboratory.csv_upload,name='csv_upload'),

    # //////////////////////////////////////////////////////
    path('lab_microscopy',laboratory.lab_microscopy,name='lab_microscopy'),
    path('lab_hematology',laboratory.lab_hematology,name='lab_hematology'),
    path('lab_serology',laboratory.lab_serology,name='lab_serology'),
    path('lab_chemistry',laboratory.lab_chemistry,name='lab_chemistry'),
    path('lab_rapidtest',laboratory.lab_rapidtest,name='lab_rapidtest'),
    path('lab_bacteriology',laboratory.lab_bacteriology,name='lab_bacteriology'),
    path('lab_opd',laboratory.lab_opd,name='lab_opd'),
    path('lab_opdxt_walkin',laboratory.lab_opdxt_walkin,name='lab_opdxt_walkin'),
    path('lab_opdxt_opd',laboratory.lab_opdxt_opd,name='lab_opdxt_opd'),
    path('lab_reception',laboratory.lab_reception,name='lab_reception'),
    path('<str:enctr>/<str:orderid>/unseen_lab_request_details',laboratory.unseen_lab_request_details,name='unseen_lab_request_details'),
    path('<str:enctr>/<str:orderid>/seen_lab_request_details',laboratory.seen_lab_request_details,name='seen_lab_request_details'),
    path('<str:key>/<str:enctr>/<str:orderid>/lab_request_confirmation',laboratory.lab_request_confirmation,name='lab_request_confirmation'),
    path('<str:key>/<str:enctr>/<str:orderid>/lab_request_undo',laboratory.lab_request_undo,name='lab_request_undo'),
    path('<str:key>/<str:enctr>/<str:orderid>/lab_request_reject',laboratory.lab_request_reject,name='lab_request_reject'),
    path('<str:enctr>/<str:orderid>/lab_request_confirm_all',laboratory.lab_request_confirm_all,name='lab_request_confirm_all'),
    path('<str:enctr>/<str:orderid>/<str:ptype>generate_ctr',laboratory.generate_ctr,name='generate_ctr'),
    path('<str:key>/<str:orderid>/<str:enctr>/to_process',laboratory.to_process,name='to_process'),

    ################# OPD LINK
    path('get_opd',laboratory.get_opd,name='get_opd'),
    path('opd_labrequest',laboratory.opd_labrequest,name='opd_labrequest'),
    path('getTotal',laboratory.getTotal,name='getTotal'),
    path('opd_release_result',laboratory.opd_release_result,name='opd_release_result'),
    ################# BACTERIOLOGY
    path('load_bacti',laboratory.load_bacti,name='load_bacti'),
    path('get_kit',laboratory.get_kit,name='get_kit'),
    path('change_kit',laboratory.change_kit,name='change_kit'),
    path('addkit',laboratory.addkit,name='addkit'),
    path('bacti_sentToProcess',laboratory.bacti_sentToProcess,name='bacti_sentToProcess'),
    path('save_rapid',laboratory.save_rapid,name='save_rapid'),
    path('get_rapidResult',laboratory.get_rapidResult,name='get_rapidResult'),
    ################ RECEPTION
    path('update_ctr',laboratory.update_ctr,name='update_ctr'),

    path('release_test',laboratory.release_test,name='release_test'),
    path('torealese_cnt',laboratory.torealese_cnt,name='torealese_cnt'),
    path('get_torelease',laboratory.get_torelease,name='get_torelease'),
    path('load_accept_req',laboratory.load_accept_req,name='load_accept_req'),
    path('request_notif',laboratory.request_notif,name='request_notif'),
    path('gen_ctr',laboratory.gen_ctr,name='gen_ctr'),
    path('recep_update_sample',laboratory.recep_update_sample,name='recep_update_sample'),
    path('test_endorsement',laboratory.test_endorsement,name='test_endorsemen'),
    path('test_cancel',laboratory.test_cancel,name='test_cancel'),
    path('get_endorsement',laboratory.get_endorsement,name='get_endorsement'),
    path('release_result',laboratory.release_result,name='release_result'),
    path('accept_endorsement',laboratory.accept_endorsement,name='accept_endorsement'),
    path('charge_now',laboratory.charge_now,name='charge_now'),
    path('<str:encc>/<str:ordid>/<str:code>/chargeslip',laboratory.chargeslip, name='chargeslip'),
    #################  HEMATOLOGY
    path('load_hema',laboratory.load_hema,name='load_hema'),
    path('hema_sentToProcess',laboratory.hema_sentToProcess,name='hema_sentToProcess'),
    path('cbc_uploads',laboratory.cbc_uploads,name='cbc_uploads'),
    path('cbcup_save',laboratory.cbcup_save,name='cbcup_save'),

    ################# CHEMISTRY
    path('load_chemi',laboratory.load_chemi,name='load_chemi'),
    path('load_lastmeal',laboratory.load_lastmeal,name='load_lastmeal'),
    path('chem_sentToProcess',laboratory.chem_sentToProcess,name='chem_sentToProcess'),
    path('chem_onprocess',laboratory.chem_onprocess,name='chem_onprocess'),
    path('chem_completed',laboratory.chem_completed,name='chem_completed'),
    path('chem_get_lastmeal',laboratory.chem_get_lastmeal,name='chem_get_lastmeal'),
    path('load_chem_count',laboratory.load_chem_count,name='load_chem_count'),
    path('getlabtest',laboratory.getlabtest,name='getlabtest'),
    ################ SENT TEST TO PROCESS
    path('sent_to_process',laboratory.sent_to_process,name='sent_to_process'),

    # ////ajax
    path('get_micro',laboratory.get_micro,name='get_micro'),
    path('load_microscopy',laboratory.load_microscopy,name='load_microscopy'),
    path('get_request',laboratory.get_request,name='get_request'),
    path('view_ua_toAddResult',laboratory.view_ua_toAddResult,name='view_ua_toAddResult'),
    path('save_ua_result',laboratory.save_ua_result,name='save_ua_result'),
    path('save_fa_result',laboratory.save_fa_result,name='save_fa_result'),
    path('save_occult',laboratory.save_occult,name='save_occult'),
    path('get_fa_resultdata',laboratory.get_fa_resultdata,name='get_fa_resultdata'),
    path('get_ua_resultdata',laboratory.get_ua_resultdata,name="get_ua_resultdata"),
    path('get_preg_result',laboratory.get_preg_result,name='get_preg_result'),
    path('save_vefify_ua_result',laboratory.save_vefify_ua_result,name='save_vefify_ua_result'),
    path('save_preg_res',laboratory.save_preg_res,name='save_preg_res'),
    path('save_vpreg_res',laboratory.save_vpreg_res,name='save_vpreg_res'),
    path('view_labrequest',laboratory.view_labrequest,name='view_labrequest'),

    # ////// laboratory Result
    path('laboratory/rapidtest',laboratory.main_rapidtest,name='main_rapidtest'),
    # 404
    path('errpage',laboratory.errpage,name='errpage'),
    ############# RESULT A4 size
    path('labres_chem/<str:toecode>/<str:orderid>/<str:encc>',laboratory.labres_chem,name='labres_chem'),
    path('labres_hema',laboratory.labres_hema,name='labres_hema'),
    path('laboratory/result/cbc/<str:ward>/<str:physician>/<str:orderid>/<str:encc>',laboratory.cbc_result,name='cbc_result'),
    path('laboratory/result/immuno/<str:ward>/<str:physician>/<str:orderid>/<str:encc>',laboratory.immuno_result,name='immuno_result'),
    path('laboratory/result/serology/<str:ward>/<str:physician>/<str:orderid>/<str:encc>',laboratory.serology_result,name='serology_result'),
    path('laboratory/result/microbiology/<str:ward>/<str:physician>/<str:orderid>/<str:encc>',laboratory.bacteriology_result,name='bacteriology_result'),

    path('laboratory/result/serology',laboratory.sero_result,name='sero_result'),
    path('laboratory/result/bacteriology',laboratory.bacte_result,name='bacte_result'),

    path('lab_result',laboratory.result_temp,name='result_temp'),
    path('result_template',laboratory.result_template,name='result_template'),
    # ///////////result template
    path('laboratory/result/rapidtest/<str:toecode>/<str:orderid>/<str:encc>/<str:prikey>',lab_result.result_RDT,name='result_RDT'),
    path('laboratory/result/urinalysis/<str:encc>/<str:orderid>',lab_result.result_Urinalysis,name='result_Urinalysis'),
    path('laboratory/result/fecalysis/<str:encc>/<str:orderid>/<str:proccode>/<str:toecode>/<str:ward>',laboratory.result_Fecalysis,name='result_Fecalysis'),
    # ///////////// HEMATHOLOGY
     path('laboratory/result/hematology',lab_result.result_hematology,name='result_hematology'),
     path('laboratory/result/coagulation',lab_result.result_coagulation,name='result_coagulation'),
     path('laboratory/result/obf_hematology',lab_result.result_obf_hematology,name='result_obf_hematology'),
     path('hema_onprocess',laboratory.hema_onprocess,name='hema_onprocess'),
     path('get_hema_count',laboratory.get_hema_count,name='get_hema_count'),
     path('save_cbc',laboratory.save_cbc,name='save_cbc'),
     path('getCbcResult',laboratory.getCbcResult,name='getCbcResult'),

    #################### MICROBIOLOGY
    path('lab_microbiology',laboratory.lab_microbiology,name='lab_microbiology'),
    path('load_biology',laboratory.load_biology,name='load_biology'),
    path('bio_sentToProcess',laboratory.bio_sentToProcess,name='bio_sentToProcess'),
    path('save_bio',laboratory.save_bio,name='save_bio'),
    path('get_bactiview',laboratory.get_bactiview,name='get_bactiview'),
    path('get_bactiResult',laboratory.get_bactiResult,name='get_bactiResult'),
    
    #  ///////////////////IMMUNOLOGY

    path('lab_immuno',laboratory.lab_immuno,name='lab_immuno'),
    path('load_immuno',laboratory.load_immuno,name='load_immuno'),
    path('immuno_sentToProcess',laboratory.immuno_sentToProcess,name='immuno_sentToProcess'),
    path('save_immuno',laboratory.save_immuno,name='save_immuno'),
    path('get_immunoResult',laboratory.get_immunoResult,name='get_immunoResult'),
    path('get_immunview',laboratory.get_immunview,name='get_immunview'),
    path('immuno_ToProcess',laboratory.immuno_ToProcess,name='immuno_ToProcess'),


    #################### SEROLOGY
    path('load_sero',laboratory.load_sero,name='load_sero'),
    path('sero_sentToProcess',laboratory.sero_sentToProcess,name='sero_sentToProcess'),
    path('save_sero',laboratory.save_sero,name='save_sero'),
    path('get_seroview',laboratory.get_seroview,name='get_seroview'),
    path('get_seroResult',laboratory.get_seroResult,name='get_seroResult'),

    #  /////////////CHEMISTRY
    path('save_chem_result',laboratory.save_chem_result,name='save_chem_result'),
    # path('<str:encc>/<str:ordid>/chargeslip',laboratory.charge_slip,name='charge_slip'),
    #/////////// PRINT REQUEST
    path('lab_request_print/<str:encc>/<str:orderid>/<str:ward>',laboratory.lab_request_print,name='lab_request_print'),

    ######################### LABORATORY KIT
    path('lab_kit',laboratory.lab_kit,name='lab_kit'),
    path('load_kit',laboratory.load_kit,name='load_kit'),
    

    path('<str:enctr>/patientlabcharges', main.patient_laboratory_charges, name='patientlabcharges'),
    path('addLabCharges', main.addLabCharges, name='addLabCharges'),
    path('delLabCharges', main.delLabCharges, name='delLabCharges'),
    path('<str:enctr>/loadpatientlabcharges', main.load_laboratory_charges, name='loadpatientlabcharges'),
    path('<str:enctr>/printlabcharges', main.printLabCharges, name='printlabcharges'),
    path('<str:enctr>/printlatestlabcharges', main.printLatestLabCharges, name='printlatestlabcharges'),
    path('<str:enctr>/charges', main.charges, name='charges'),
    path('<str:chargecode>/<str:type>/<str:enctr>/editcharges', main.editcharges, name='editcharges'),
    path('<str:chargecode>/<str:enctr>/deletecharges', main.deletecharges, name='deletecharges'),
    path('<str:enctr>/newcharges', main.newcharges, name='newcharges'),
    path('addCharges', main.addCharges, name='addCharges'),
    path('radiology', main.radiology, name='radiology'),
    path('radiologyopd', main.radiology_opd, name='radiologyopd'),
    path('radiologyer', main.radiology_er, name='radiologyer'),
    path('<str:enctr>/patientradcharges', main.patient_radiology_charges, name='patientradcharges'),
    path('addRadCharges', main.addRadCharges, name='addRadCharges'),
    path('delRadCharges', main.delRadCharges, name='delRadCharges'),
    path('<str:enctr>/printradcharges', main.printRadCharges, name='printradcharges'),
    path('<str:enctr>/printlatestradcharges', main.printLatestRadCharges, name='printlatestradcharges'),
    path('<str:enctr>/radpatientexam', main.rad_patient_exam, name='patradexam'),
    path('<str:enctr>/loadpatientradcharges', main.load_radiology_charges, name='loadpatientradcharges'),
    path('billing', main.billing, name='billing'),
    path('<str:enctr>/bill', main.patient_bill, name='bill'),
    path('maipreport', main.billing_maip_report, name='maipreport'),
    path('maipexcel', main.billing_maip_excel_report, name='maipexcel'),
    path('<str:enctr>/dialysisbill', main.print_dialy_detailed_patient_bill, name='dialysisbill'),
    path('<str:enctr>/loadallcharges', main.load_all_charges, name='loadallcharges'),
    path('deletecharges', main.delCharges, name='deletecharges'),
    path('discount', main.discounts, name='discounts'),
    path('<str:enctr>/patient_discount', main.patient_discount, name='patient_discount'),
    path('<str:enctr>/pfdisc', main.add_pf_discount, name='pfdisc'),
    path('<str:enctr>/<str:licno>/<str:type>/delpfdisc', main.del_pf_discount, name='delpfdisc'),
    path('<str:enctr>/<str:hpercode>/add_discount', main.add_discount, name='add_discount'),
    path('<str:enctr>/<str:disc_type>/delete_discount', main.delete_discount, name='delete_discount'),
    path('<str:enctr>/printbill', main.print_patient_bill, name='printbill'),
    path('<str:enctr>/printdetailedbill', main.print_patient_detailed_bill, name='printdetailedbill'),
    path('<str:enctr>/printdialysispatientbill', main.print_dialysis_patient_bill, name='printdialysispatientbill'),
    path('<str:enctr>/billingdetailedbillexcel', main.billing_detailed_bill_excel, name='billingdetailedbillexcel'),
    path('<str:enctr>/diagnosis', main.patient_diagnosis, name='diagnosis'),
    path('<str:enctr>/<str:uid>/delete_diagnosis', main.delete_diagnosis, name='deleteDiagnosis'),
    path('<str:enctr>/caserate', main.caserate, name='caserate'),
    path('<str:enctr>/<str:typ>/deletecaserate', main.deletecaserate, name='deletecaserate'),
    path('<str:enctr>/proffee', main.proffee, name='proffee'),
    path('<str:enctr>/addproffee', main.addProffee, name='addproffee'),
    path('<str:enctr>/<str:licno>/deleteProffee', main.deleteProffee, name='deleteProffee'),
    path('pharmacy', main.pharmacy, name='pharmacy'),
    path('<str:enctr>/loadPrescription', main.load_prescription, name='loadPrescription'),
    path('releasemeds', main.release_meds, name='releasemeds'),
    path('undomeds', main.undo_meds, name='undomeds'),
    path('<str:enctr>/printprescription', main.print_prescription, name='printprescription'),
    path('enurse', enurse.enurse, name='enurse'),
    path('<str:enctr>/enursepatient', enurse.enurse_patient, name='enursepatient'),
    path('<str:enctr>/addmgh', enurse.addmgh, name='addmgh'),
    path('<str:enctr>/editmgh', enurse.editmgh, name='editmgh'),
    path('nurseassignment', enurse.nurse_assignment, name='nurseassignment'),
    path('<str:enctr>/nursecharges', enurse.nurse_charges, name='nursecharges'),
    path('<str:enctr>/loadnursecharges', enurse.load_nurse_charges, name='loadnursecharges'),
    path('<str:enctr>/<str:code>/nursedeletecharges', enurse.nurse_delete_charges, name='nursedeletecharges'),
    path('profile', main.profile, name='profile'),
    path('changepw', main.changepw, name='changepw'),
    path('<str:uid>/clearance', main.clearance, name='clearance'),
    path('<str:uid>/clearanceundo', main.clearance_undo, name='clearanceundo'),
    path('cashier', main.cashier, name='cashier'),
    path('<str:no>/rfid', main.rfid, name='rfid'),
    path('er', er.er, name='er'),
    path('erlist', er.erlist, name='erlist'),
    path('ersearch', er.ersearch, name='ersearch'),
    path('<str:no>/erlog', er.erlogpatient, name='erlog'),
    path('<str:no>/erpatientdetails', er.patientDetails, name='erpatientdetails'),
    path('<str:no>/<str:enctr>/erlogdetails', er.erpatientlog, name='erlogdetails'),
    path('<str:no>/<str:enctr>/erdischarged', er.erpatientdischarged, name='erdischarged'),
    path('<str:enctr>/printerrecord', er.printerrecord, name='printerrecord'),
    path('dialysis', main.dialysis, name='dialysis'),
    path('<str:no>/dialysisenrollment', main.dialysisenrollment, name='dialysisEnrollment'),
    path('<str:no>/dialysisenrolled', main.dialysisenrolled, name='dialysisenrolled'),
    path('<str:enctr>/dialysisDischarged', main.dialysisDischarged, name='dialysisDischarged'),
    path('dialysislog', main.dialysislog, name='dialysislog'),
    path('<str:enctr>/dialysisconsultation', main.dialysisConsultation, name='dialysisconsultation'),
    path('socialservice', main.social_service, name='socialservice'),
    path('patientsearchmss', main.patient_search_mss, name='patientsearchmss'),
    path('<str:hpercode>/msspatientencounter', main.mss_patient_encounter, name='msspatientencounter'),
    path('<str:enctr>/msspatientdetails', main.mss_patient_details, name='msspatientdetails'),
    path('reports', main.reports, name='reports'),
    path('erreferral', main.re_er_referral, name='erreferral'),
    path('reerincoming', main.re_er_incoming, name='reerincoming'),
    path('reoutgoing', main.re_refer_outgoing, name='reoutgoing'),
    path('login', main.login, name='login'),
    path('logout', main.logout, name='logout'),
    path('him', him.him, name='him'),
    path('digitizesearch', him.digitize_search, name='digitizesearch'),
    path('<str:code>/digitizepatient', him.digitize_patient, name='digitizepatient'),
    path('<str:enctr>/uploadrecord', him.upload, name='uploadrecord'),
    path('<str:enctr>/digitizerecord', him.digitize_record, name='digitizerecord'),
    path('lab-patient-search', laboratory.laboratory_patient_search, name='lab-patient-search'),
    path('er-tat-report', er.ertat_report, name='er-tat-report'),
    path('<str:date>/er-tat-daily-report', er.er_tat_daily_report, name='er-tat-daily-report'),
    path('re-daily-movement', main.re_daily_movement, name='re-daily-movement'),
    path('re-bills-rendered', main.re_bills_rendered, name='re-bills-rendered'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)